---

- name: K3s cluster
  hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - prereq
    - download
    - raspbian
    - ubuntu

- name: Master node
  hosts: master
  become: yes
  ansible.builtin.include_role:
    name: Master
    tasks_from: k3s/master

- name: Nodes
  hosts: node
  become: yes
  ansible.builtin.include_role:
    name: Node
    tasks_from: k3s/node
