---

- name: K3s cluster
  hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - ansible.builtin.include_role:
        name: Pre-requisites
        tasks_from: prereq
    - ansible.builtin.include_role:
        name: Download software
        tasks_from: download
    - ansible.builtin.include_role:
        name: Raspbian OS
        tasks_from: raspbian
    - ansible.builtin.include_role:
        name: Ubunutu OS
        tasks_from: ubuntu

- name: Master node
  hosts: master
  become: yes
  ansible.builtin.include_role:
    name: Master
    tasks_from: k3s/master

- name: Nodes
  hosts: node
  become: yes
  ansible.builtin.include_role:
    name: Node
    tasks_from: k3s/node
