---

- name: K3s cluster
  hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - ansible.builtin.include_role: prereq
    - ansible.builtin.include_role: download
    - ansible.builtin.include_role: raspbian
    - ansible.builtin.include_role: ubuntu

- name: Master node
  hosts: master
  become: yes
  ansible.builtin.include_role:
          name: Master
          tasks_from: k3s/master

- name: Nodes
  hosts: node
  become: yes
  ansible.builtin.include_role: 
    name: Node
    tasks_from: k3s/node
