---

- name: K3s cluster
  hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspbian
    - role: ubuntu

- name: Master node
  hosts: master
  become: yes
  roles:
    - role: k3s/master

- name: Nodes
  hosts: node
  become: yes
  roles:
    - role: k3s/node
