---
- name: Enable cgroup via boot commandline if not already enabled for Ubuntu on ARM
  lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: yes
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: reboot-arm64
  when:
    - ansible_distribution == 'Ubuntu'
    - ( ansible_facts.architecture is search("arm") or
        ansible_facts.architecture is search("aarch64") )

# Next task became a handler known as 'reboot-arm64'
#- name: Reboot to enable cgroups for Ubuntu on ARM
#  reboot:
#  when:
#    - ansible_distribution == 'Ubuntu'
#    - ( ansible_facts.architecture is search("arm") or
#        ansible_facts.architecture is search("aarch64") )
