---

- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Create directory .kube
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"

- name: Create kubectl/crictl symlinks
  file:
    src: /usr/local/bin/k3s
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - kubectl
    - crictl

- name: fetch the ~/.kube/config file
  fetch:
    src: ~{{ ansible_user }}/.kube/config
    dest: ~{{ ansible_user }}/.kube/
    flat: yes
  when: inventory_hostname == 'master'
